from __future__ import annotations

import html
import re
from collections import Counter
from dataclasses import dataclass
from datetime import datetime
from io import BytesIO
from typing import Optional

import requests
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlalchemy import desc, func, or_
from sqlmodel import Session, select

from app.models.activity import Activity
from app.models.project import Project
from app.models.transformation import Transformation
from app.models.user import User


@dataclass
class ProjectSummaryRow:
    name: str
    created_at: datetime
    updated_at: datetime
    generation_count: int
    top_style: str


def _scalar_count(value: object) -> int:
    if isinstance(value, tuple):
        value = value[0]
    return int(value or 0)


def _format_datetime(value: Optional[datetime]) -> str:
    if not value:
        return "Not available"
    return value.strftime("%B %d, %Y at %I:%M %p")


def _safe(value: Optional[str], fallback: str = "Not available") -> str:
    return html.escape((value or "").strip() or fallback)


def _plain(value: Optional[str], fallback: str = "Not available") -> str:
    return (value or "").strip() or fallback


def _filename_part(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "_", value).strip("_")
    return cleaned or "account"


def account_summary_filename(user: User) -> str:
    base = user.user_name or user.email or user.firebase_uid
    return f"Account_Summary_{_filename_part(base)}.pdf"


def _load_profile_photo(photo_url: Optional[str]) -> Optional[Image]:
    if not photo_url:
        return None
    try:
        response = requests.get(photo_url, timeout=8)
        response.raise_for_status()
        content_type = response.headers.get("content-type", "")
        if content_type and not content_type.lower().startswith("image/"):
            return None
        image = Image(BytesIO(response.content), width=0.95 * inch, height=0.95 * inch)
        image.hAlign = "LEFT"
        return image
    except Exception as exc:
        print(f"[account_summary] profile photo fallback used: {exc}")
        return None


def _style_counter_for_project(db: Session, project_id) -> Counter[str]:
    styles = db.exec(
        select(Transformation.style_name).where(Transformation.project_id == project_id)
    ).all()
    return Counter((style or "Unspecified").strip() or "Unspecified" for style in styles)


def _build_project_rows(db: Session, user: User) -> list[ProjectSummaryRow]:
    projects = db.exec(
        select(Project)
        .where(Project.user_id == user.user_id)
        .order_by(desc(Project.project_last_updated))
    ).all()

    rows: list[ProjectSummaryRow] = []
    for project in projects:
        count = _scalar_count(
            db.exec(
                select(func.count()).select_from(Transformation).where(
                    Transformation.project_id == project.project_id
                )
            ).one()
        )
        styles = _style_counter_for_project(db, project.project_id)
        top_style = styles.most_common(1)[0][0] if styles else "No generations yet"
        rows.append(
            ProjectSummaryRow(
                name=project.project_name,
                created_at=project.project_creation_time,
                updated_at=project.project_last_updated,
                generation_count=count,
                top_style=top_style,
            )
        )
    return rows


def _user_generation_filter(user: User, project_ids: list) -> object:
    if project_ids:
        return or_(
            Transformation.user_id == user.user_id,
            Transformation.project_id.in_(project_ids),
        )
    return Transformation.user_id == user.user_id


def _footer(canvas, doc) -> None:
    canvas.saveState()
    width, _ = A4
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.drawString(doc.leftMargin, 0.38 * inch, "Generated by DeClutter")
    canvas.drawRightString(width - doc.rightMargin, 0.38 * inch, f"Page {doc.page}")
    canvas.restoreState()


def generate_account_summary_pdf(db: Session, user: User) -> bytes:
    generated_at = datetime.utcnow()
    project_rows = _build_project_rows(db, user)
    user_project_ids = [
        project.project_id
        for project in db.exec(select(Project).where(Project.user_id == user.user_id)).all()
    ]
    generation_filter = _user_generation_filter(user, user_project_ids)
    total_generations = _scalar_count(
        db.exec(
            select(func.count()).select_from(Transformation).where(generation_filter)
        ).one()
    )
    styles = db.exec(
        select(Transformation.style_name).where(generation_filter)
    ).all()
    style_counts = Counter((style or "Unspecified").strip() or "Unspecified" for style in styles)
    biggest_project = max(project_rows, key=lambda p: p.generation_count, default=None)
    most_recent_login = db.exec(
        select(Activity)
        .where(Activity.user_id == user.user_id, Activity.action_type == "login")
        .order_by(desc(Activity.timestamp))
        .limit(1)
    ).first()

    account_created_at = user.account_created_at or user.created_at
    last_sign_in_at = (most_recent_login.timestamp if most_recent_login else None) or user.last_sign_in_at

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.62 * inch,
        leftMargin=0.62 * inch,
        topMargin=0.65 * inch,
        bottomMargin=0.72 * inch,
        title="DeClutter Account Summary",
        author="DeClutter",
    )

    base = getSampleStyleSheet()
    styles_pdf = {
        "title": ParagraphStyle(
            "SummaryTitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#111827"),
            spaceAfter=8,
        ),
        "subtitle": ParagraphStyle(
            "SummarySubtitle",
            parent=base["Normal"],
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#6B7280"),
            spaceAfter=16,
        ),
        "section": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#1F2937"),
            spaceBefore=12,
            spaceAfter=7,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["BodyText"],
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#374151"),
        ),
        "muted": ParagraphStyle(
            "Muted",
            parent=base["BodyText"],
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#6B7280"),
        ),
        "center": ParagraphStyle(
            "Center",
            parent=base["BodyText"],
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=18,
            textColor=colors.white,
        ),
        "right": ParagraphStyle(
            "Right",
            parent=base["BodyText"],
            alignment=TA_RIGHT,
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#6B7280"),
        ),
    }

    story = [
        Paragraph("DeClutter - Account Summary", styles_pdf["title"]),
        Paragraph(
            f"Generated on {_format_datetime(generated_at)} UTC",
            styles_pdf["subtitle"],
        ),
    ]

    photo = _load_profile_photo(user.photo_url)
    if photo is None:
        initials = "".join(part[0] for part in (user.user_name or user.email or "U").split()[:2]).upper()
        photo = Table(
            [[Paragraph(_safe(initials or "U"), styles_pdf["center"])]],
            colWidths=[0.95 * inch],
            rowHeights=[0.95 * inch],
        )
        photo.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#4F46E5")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ]
            )
        )

    profile_table = Table(
        [
            [
                photo,
                [
                    Paragraph("<b>Name</b><br/>" + _safe(user.user_name), styles_pdf["body"]),
                    Spacer(1, 7),
                    Paragraph("<b>Email</b><br/>" + _safe(user.email), styles_pdf["body"]),
                ],
            ]
        ],
        colWidths=[1.2 * inch, 5.0 * inch],
    )
    profile_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#E5E7EB")),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                ("TOPPADDING", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ]
        )
    )
    story.extend([Paragraph("User Profile", styles_pdf["section"]), profile_table])

    metadata_table = Table(
        [
            ["Account creation date", _format_datetime(account_created_at)],
            ["Most recent sign-in", _format_datetime(last_sign_in_at)],
        ],
        colWidths=[2.1 * inch, 4.1 * inch],
    )
    metadata_table.setStyle(_basic_table_style())
    story.extend([Paragraph("Account Details", styles_pdf["section"]), metadata_table])

    stat_rows = [["Metric", "Value"], ["Total number of generations", str(total_generations)]]
    stats_table = Table(stat_rows, colWidths=[3.2 * inch, 3.0 * inch])
    stats_table.setStyle(_basic_table_style(header=True))
    story.extend(
        [
            Paragraph("Generation Statistics", styles_pdf["section"]),
            Paragraph(
                "",
                styles_pdf["muted"],
            ),
            Spacer(1, 6),
            stats_table,
        ]
    )

    story.append(Paragraph("Most Used Generation Styles", styles_pdf["section"]))
    if style_counts:
        style_rows = [["Style", "Count", "Percentage"]]
        for style_name, count in style_counts.most_common(5):
            percentage = (count / total_generations * 100) if total_generations else 0
            style_rows.append([style_name, str(count), f"{percentage:.1f}%"])
        style_table = Table(style_rows, colWidths=[3.3 * inch, 1.2 * inch, 1.7 * inch])
        style_table.setStyle(_basic_table_style(header=True))
        story.append(style_table)
    else:
        story.append(Paragraph("No generations have been created yet.", styles_pdf["body"]))

    story.append(Paragraph("Projects Overview", styles_pdf["section"]))
    if project_rows:
        project_table_rows = [["Project", "Created", "Last updated", "Generations", "Top style"]]
        for row in project_rows:
            project_table_rows.append(
                [
                    _plain(row.name),
                    row.created_at.strftime("%Y-%m-%d"),
                    row.updated_at.strftime("%Y-%m-%d"),
                    str(row.generation_count),
                    _plain(row.top_style),
                ]
            )
        projects_table = Table(
            project_table_rows,
            colWidths=[1.8 * inch, 1.0 * inch, 1.1 * inch, 0.9 * inch, 1.4 * inch],
            repeatRows=1,
        )
        projects_table.setStyle(_basic_table_style(header=True))
        story.append(projects_table)
    else:
        story.append(Paragraph("No projects have been created yet.", styles_pdf["body"]))

    story.append(Paragraph("Biggest Project", styles_pdf["section"]))
    definition = "Biggest project is defined as the project with the highest number of generations."
    if biggest_project and biggest_project.generation_count > 0:
        biggest_table = Table(
            [
                #["Definition", definition],
                ["Project", _plain(biggest_project.name)],
                ["Generations", str(biggest_project.generation_count)],
                ["Top style", _plain(biggest_project.top_style)],
                ["Last updated", _format_datetime(biggest_project.updated_at)],
            ],
            colWidths=[1.5 * inch, 4.7 * inch],
        )
        biggest_table.setStyle(_basic_table_style())
        story.append(KeepTogether([biggest_table]))
    else:
        story.append(Paragraph(f"{definition} No project has generations yet.", styles_pdf["body"]))

    story.extend(
        [
            Spacer(1, 12),
            Paragraph(
                "",
                styles_pdf["muted"],
            ),
        ]
    )

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


def _basic_table_style(header: bool = False) -> TableStyle:
    commands = [
        ("BOX", (0, 0), (-1, -1), 0.45, colors.HexColor("#D1D5DB")),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#E5E7EB")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#374151")),
    ]
    if header:
        commands.extend(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    return TableStyle(commands)
