import type { CSSProperties } from "react";
import TopBar from "../components/TopBar";
import Footer from "../components/Footer";

function TermsOfService() {
  const s: Record<string, CSSProperties> = {
    page: {
      display: "flex", flexDirection: "column", minHeight: "100vh",
      backgroundColor: "var(--color-bg-base)", transition: "background-color 0.3s ease",
      fontFamily: "'Alata', sans-serif",
    },
    heroTitle: {
      fontSize: "2.8rem", fontWeight: 800, letterSpacing: "-1px", lineHeight: 1.15,
      color: "var(--color-text-primary)", margin: "0 0 16px",
    },
    heroSub: {
      fontSize: "1.05rem", lineHeight: 1.7, margin: "0 0 8px",
      color: "var(--color-text-secondary)",
    },
    main: { flex: 1, padding: "70px 24px", background: "var(--color-bg-base)" },
    card: {
      maxWidth: "1080px", margin: "0 auto",
    },
    updated: { fontSize: "0.85rem", color: "var(--color-text-secondary)", margin: "0 0 32px" },
    sectionTitle: {
      fontSize: "1.3rem", fontWeight: 800, color: "var(--color-text-primary)",
      margin: "32px 0 12px",
    },
    paragraph: {
      fontSize: "0.95rem", lineHeight: 1.8, color: "var(--color-text-secondary)", margin: "0 0 12px",
    },
    list: {
      fontSize: "0.95rem", lineHeight: 1.8, color: "var(--color-text-secondary)",
      margin: "0 0 12px", paddingLeft: "20px",
    },
  };

  const sections = [
    {
      title: "1. Acceptance of Terms",
      body: (
        <p style={s.paragraph}>
          By accessing or using DeClutter, you agree to be bound by these Terms of Service. If you
          do not agree with any part of these terms, please do not use our service.
        </p>
      ),
    },
    {
      title: "2. Description of Service",
      body: (
        <p style={s.paragraph}>
          DeClutter is an AI-powered interior design tool that lets you upload a room photo, choose a
          style, and receive an AI-transformed result. The service is provided on an "as is" basis
          and may be updated, changed, or discontinued at any time.
        </p>
      ),
    },
    {
      title: "3. User Accounts",
      body: (
        <>
          <p style={s.paragraph}>
            To use certain features you must create an account. You agree to:
          </p>
          <ul style={s.list}>
            <li>Provide accurate and complete information when signing up.</li>
            <li>Keep your login credentials secure and confidential.</li>
            <li>Be responsible for all activity that occurs under your account.</li>
            <li>Notify us promptly of any unauthorized use of your account.</li>
          </ul>
        </>
      ),
    },
    {
      title: "4. Acceptable Use",
      body: (
        <>
          <p style={s.paragraph}>When using DeClutter, you agree not to:</p>
          <ul style={s.list}>
            <li>Upload content you do not have the right to use.</li>
            <li>Upload unlawful, offensive, or infringing material.</li>
            <li>Attempt to disrupt, reverse-engineer, or abuse the service.</li>
            <li>Use the service for any illegal or unauthorized purpose.</li>
          </ul>
        </>
      ),
    },
    {
      title: "5. User Content",
      body: (
        <p style={s.paragraph}>
          You retain ownership of the photos you upload. By uploading content, you grant DeClutter a
          limited license to process those images solely to provide the transformation you
          requested. You are responsible for ensuring you have the rights to any content you submit.
        </p>
      ),
    },
    {
      title: "6. Intellectual Property",
      body: (
        <p style={s.paragraph}>
          The DeClutter name, branding, software, and design are owned by DeClutter, Inc. and are
          protected by applicable intellectual property laws. You may not copy, modify, or
          redistribute any part of the service without prior written permission.
        </p>
      ),
    },
    {
      title: "7. AI-Generated Results",
      body: (
        <p style={s.paragraph}>
          Transformations are generated by an AI model and are provided for inspiration and
          visualization purposes only. Results may vary and are not guaranteed to be accurate,
          buildable, or suitable for any particular purpose.
        </p>
      ),
    },
    {
      title: "8. Limitation of Liability",
      body: (
        <p style={s.paragraph}>
          To the fullest extent permitted by law, DeClutter shall not be liable for any indirect,
          incidental, or consequential damages arising from your use of the service. The service is
          provided without warranties of any kind.
        </p>
      ),
    },
    {
      title: "9. Termination",
      body: (
        <p style={s.paragraph}>
          We may suspend or terminate your access to DeClutter at any time if you violate these
          terms or use the service in a way that could harm us or other users. You may stop using
          the service and delete your account at any time.
        </p>
      ),
    },
    {
      title: "10. Changes to These Terms",
      body: (
        <p style={s.paragraph}>
          We may update these Terms of Service from time to time. Any changes will be posted on this
          page with an updated revision date. Continued use of the service after changes means you
          accept the revised terms.
        </p>
      ),
    },
    {
      title: "11. Contact Us",
      body: (
        <p style={s.paragraph}>
          If you have any questions about these Terms of Service, please visit our Contact page or
          email us at hello@declutter.app.
        </p>
      ),
    },
  ];

  return (
    <div style={s.page}>
      <style>{`
        @media (max-width: 768px) {
          .pp-title { font-size: 2rem !important; }
        }
      `}</style>

      <TopBar showSignIn={true} />

      {/* Main */}
      <section style={s.main}>
        <div style={s.card} className="pp-card">
          <h1 style={s.heroTitle} className="pp-title">Terms of Service</h1>
          <p style={s.heroSub}>
            Please read these terms carefully. They govern your use of DeClutter and the AI-powered
            transformations we provide.
          </p>
          <p style={s.updated}>Last updated: June 6, 2026</p>
          {sections.map(({ title, body }) => (
            <div key={title}>
              <h2 style={s.sectionTitle}>{title}</h2>
              {body}
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </div>
  );
}

export default TermsOfService;
